### ISSUE TITLE
Finishing installation error.

### ISSUE THREAD

**Issue by grancardy** [GR360RY/snipeit-ansible#10]
Hi!

I´ve a problem finishing the installation with the script.
there is the problem.

TASK: [snipeit-ansible | Clone Snipe-IT repo] *********************************
failed: [127.0.0.1] => {"failed": true}
msg: Local modifications exist in repository (force=no).

FATAL: all hosts have already failed -- aborting

The machine is a fresh installation Ubuntu x64, 14.01 LTS with LAMP server running in a viertual infrastructure.

Thanks.

**Comment by eidlyn** [comment]
I'm still having the originial problem. The line "force = no" was not in the code.

**Comment by zrunyon** [comment]
I am receiving this error when executing the script. Ubuntu 14.04

failed: [127.0.0.1] => {"failed": true}
msg: Local modifications exist in repository (force=no).

FATAL: all hosts have already failed -- aborting

Thank you.

**Comment by grancardy** [comment]
I found when you install new Ubuntu machine, do not install LAMP. 
The script install the requirements and will finish without errors.

**Comment by GR360RY** [comment]
Fixed in #15
