### ISSUE TITLE
Unable to connect. check login_user...

### ISSUE THREAD

**Issue by grancardy** [GR360RY/snipeit-ansible#11]
Hi!

I´ve installed in a fresh installation ubuntu server, and in the last step appears this error:

TASK: [snipeit-ansible | Create snipeit database] *****************************
failed: [127.0.0.1] => {"failed": true}
msg: unable to connect, check login_user and login_password are correct, or alternatively check ~/.my.cnf contains credentials

FATAL: all hosts have already failed -- aborting

Regards

**Comment by thomasneat** [comment]
I must also say I'm seeing this as well.  I've tried several things and even made the snipeit/secret account but constantly this failure. I'm trying to reverse engineer it but I do not have a whole lot of time to mess with it before moving on to other possible asset softwares to demo to my company.

**Comment by GR360RY** [comment]
Do you mysqld already installed on this systems prior to the setup ? It looks like there is an issue with connecting to the database. Please paste the full logs for me to investigate.

**Comment by thomasneat** [comment]
I'm assuming you mean mysql logs.  I checked, my logs are blank.  This is a brand new install.  I can log into mysql and create databases with the login creds I used.  I'm assuming you're creating a new distro because of the new snipe-it though because I attempted to run it again and I'm getting failures because of checked out packages.

**Comment by thomasneat** [comment]
Also, out of curiosity I installed phpMyAdmin and wordpress.  Both installed fine with mysql.  Wordpress even creates its own database.

**Comment by thomasneat** [comment]
I now cannot get past this?

TASK: [snipeit-ansible | Install php requirements with composer] **************
failed: [127.0.0.1] => {"changed": true, "cmd": "php composer.phar install", "delta": "0:00:00.197187", "end": "2015-02-23 06:12:10.342724", "rc": 1, "start": "2015-02-23 06:12:10.145537", "warnings": []}
stderr:

                                                                                
  [RuntimeException]                                                            
  Source directory /opt/snipe-it/vendor/classpreloader/classpreloader has uncommitted changes.

**Comment by GR360RY** [comment]
Fixed in #14
