### ISSUE TITLE
Grab latest stable release (from master branch) instead of the latest (frequently the develop branch)

### ISSUE THREAD

**Issue by bskertchly** [GR360RY/snipeit-ansible#13]
First off, thanks for putting this together, it really simplified my install. This is just a suggestion.

When I tried to upgrade from 1.2.5 to 1.2.6, I had a [weird issue](https://github.com/snipe/snipe-it/issues/586). I was unable to reproduce it, but I have a sneaking suspicion that it may have had something to do with grabbing development versions.

I suggest changing the task in main.yml from:

    - name: Clone Snipe-IT repo
    git: repo=https://github.com/snipe/snipe-it.git dest={{ snipeit_source }}

to:

    - name: Clone Snipe-IT repo
    git: repo=https://github.com/snipe/snipe-it.git version=master dest={{ snipeit_source }}

Or perhaps make it a variable so that people can configure which version they want?

Anyway, thanks for all the hard work that went into this. It is appreciated.

**Comment by GR360RY** [comment]
Option to add snipe-it version is added. README.md updated.
