### ISSUE TITLE
Server Error: 500 (Internal Server Error) 

### ISSUE THREAD

**Issue by suneyo21** [GR360RY/snipeit-ansible#19]
I was able to install the script without any issues, but i am having this error "Server Error: 500 (Internal Server Error)" upon accessing it, and i cant see any logs on apache.

**Comment by suneyo21** [comment]
Still having this error.  I tried a lot of changes changing permission and conf files including the article below, the worst part is no error appearing on apache logs.

http://askubuntu.com/questions/413887/403-forbidden-after-changing-documentroot-directory-apache-2-4-6

**Comment by suneyo21** [comment]
My os is Ubuntu 14.04.2 LTS

**Comment by meganeshkadam** [comment]
Hi
I faced the same issue and tried to resolve it with the help of snipe...
it seems this script does not create the database..

**Comment by diclophis** [comment]
I think this is related to changes in the artisan expect script:

https://github.com/GR360RY/snipeit-ansible/blob/50605c3e1054dcb4a409ff6bab946f6509709153/templates/artisan_expect.exp.j2#L9

**Comment by jmac810** [comment]
Here is what the output is.

<img width="689" alt="screen shot 2015-08-24 at 4 55 04 pm" src="https://cloud.githubusercontent.com/assets/13352468/9455501/b6c5707a-4a80-11e5-9448-3b75ad3c7d5e.png">

**Comment by alshawwa** [comment]
i just installed snipe-it on Ubuntu 14.0.4 results OK=27 changed=23 failed =0 

i browse to the server and i get
Whoops!
Server Error: 500 (Internal Server Error)

any quick fixes ?

**Comment by diclophis** [comment]
@alshawwa we were able to get it to run by updating the artisan expect script..

    - name: Add expect installation script for Artisan (this is custom)
      template: src=artisan_expect.exp.j2 dest={{ snipeit_source }}/artisan_expect.exp mode=0755

Then we added our custom template that looks like this:

    #### templates/artisan_expect.exp.j2
    
    #!/usr/bin/expect
    
    spawn php artisan app:install
    
    expect "Please enter your first name:" {send "{{ admin_first_name }}\r"}
    expect "Please enter your last name:" {send "{{ admin_last_name }}\r"}
    expect "Please enter your user email:" {send "{{ admin_email }}\r"}
    expect "Please enter your user password (at least 8 characters):" {send "{{ admin_password }}\r"}
    expect "Do you want to seed your database with dummy data? y/n (default is yes):" {send "yes\r"}
    expect "Do you really wish to run this command?" {send "yes\r"}
    expect "Do you really wish to run this command?" {send "yes\r"}
    
    expect eof

**Comment by alshawwa** [comment]
yup got it working 
thanks!

**Comment by ccarter2424** [comment]
Hey Guys same problem and unsure of how you have fixed it? 
What files do i need to edit?? 

Sorry total newbie!! 

Thanks in advance

**Comment by msivaklsg** [comment]
Hi Guys,

Any way someone can post detailed instructions on how to fix the 500 error?

Thank you much!

**Comment by alshawwa** [comment]
what i did was i re-ran install.sh from the snipe-it-2.x.x source  and when asked to autocreate database username and password , i chose to manually set them up  and then everything started working fine.

**Comment by msivaklsg** [comment]
Thanks. Rebooted the server, and re-ran install.sh and its working like a charm!!

Thank you! Thank you! Thank you!

**Comment by patgmac** [comment]
Has anyone figured out a fix for this yet? Re-running install.sh has not worked for me.

**Comment by alshawwa** [comment]
when you re-ran install.sh it and got to the database creation did you let the script auto generate passwords or did you set your own? 
is your server running anything else other than snipe-it ?

**Comment by patgmac** [comment]
I've tried both ways, even tried with a vagrant install. This is a brand new Ubuntu VM with nothing else on it. I've also tried deleting the db and user so the script can re-create them. 

Create MySQL accounts
mysqladmin: connect to server at 'localhost' failed
error: 'Access denied for user 'root'@'localhost' (using password: NO)'

**Comment by alshawwa** [comment]
alright let me right and test a quick install script , so you can give it a try on a new Ubuntu installation. ill keep you posted

**Comment by alshawwa** [comment]
@patgmac  try that script  , i tried it on 3 different Ubuntu flavors and it worked just fine.  


###remember to set your own sql passwords when asked by the install.sh script , do not let it auto generate passwords####

can be downloaded from http://1drv.ms/1Giahjt   , then " sudo bash snipeinst.sh" 
or 
you can sudo each command in the script file , whatever makes you feel conformable

**Comment by jmcilhargey1** [comment]
I had similar issues and had to run command below to get the database successfully set up.

/opt/snipe-it php artisan app:install 

 Issue resolved by using following link.

[https://github.com/snipe/snipe-it/issues/797](https://github.com/snipe/snipe-it/issues/797)
