### ISSUE TITLE
Missing license information

### ISSUE THREAD

**Issue by richardklose** [GR360RY/snipeit-ansible#29]
This repository does not contain a License information. 
According to GitHub's Licensing Help:

> ... without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.

Currently I am working on a playbook for deploying Snipe-IT for our company and I'd like to reuse part of your work. Because of the missing license information, I want to ask if I am allowed to reuse parts of your code.

**Comment by GR360RY** [comment]
You can use it freely. Which license would you prefer ? (BSD, Apache or MIT). Any of those licenses will be o.k by me.

**Comment by richardklose** [comment]
Thanks! I'd prefer MIT, but Apache and BSD are fine, too.

**Comment by GR360RY** [comment]
Done. You are welcome :). Please resolve this issue if the solution works for you.
